// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-GnhSeVdTgK3kIlEqaujGU0MaGfZKC4I',
    appId: '1:261691548059:web:126e748782093a6f1f013e',
    messagingSenderId: '261691548059',
    projectId: 'e-ambulance-system-001',
    authDomain: 'e-ambulance-system-001.firebaseapp.com',
    storageBucket: 'e-ambulance-system-001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkCKYfSLBEj4wLZUDOVCX4hIiauka2K9c',
    appId: '1:261691548059:android:9ba6cdf7fdd8a32c1f013e',
    messagingSenderId: '261691548059',
    projectId: 'e-ambulance-system-001',
    storageBucket: 'e-ambulance-system-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEpLl3NGjoJg569CG_bQ7DaANYDXfs6Zw',
    appId: '1:261691548059:ios:60158d3d585632f01f013e',
    messagingSenderId: '261691548059',
    projectId: 'e-ambulance-system-001',
    storageBucket: 'e-ambulance-system-001.firebasestorage.app',
    iosBundleId: 'com.ambulance.bd.ambulanceDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEpLl3NGjoJg569CG_bQ7DaANYDXfs6Zw',
    appId: '1:261691548059:ios:60158d3d585632f01f013e',
    messagingSenderId: '261691548059',
    projectId: 'e-ambulance-system-001',
    storageBucket: 'e-ambulance-system-001.firebasestorage.app',
    iosBundleId: 'com.ambulance.bd.ambulanceDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-GnhSeVdTgK3kIlEqaujGU0MaGfZKC4I',
    appId: '1:261691548059:web:2fdb2158e642bca41f013e',
    messagingSenderId: '261691548059',
    projectId: 'e-ambulance-system-001',
    authDomain: 'e-ambulance-system-001.firebaseapp.com',
    storageBucket: 'e-ambulance-system-001.firebasestorage.app',
  );
}
